/**
 * BatchRegistryV7 × REAL V23 data at PRODUCTION security (n_queries = 20).
 *
 * The generic V7 suite proves the registry logic on synthetic inner statements;
 * this one closes the remaining gap: the bundles here come from the ACTUAL V23
 * trace groups (LOG=10: 1298 cols, LOG=8: 2206 cols), generated by
 * `gen_mldsa_v23_recursive_bundles` at 20 FRI queries — the 130-bit production
 * config at which DIRECT verification no longer fits a transaction (measured in
 * docs/conclusions.md §2.3). If this finalizes, the v8 stack's on-chain half is
 * real, not an analogy from synthetic shapes.
 *
 * Fixture: v23_recursive_bundles_e2e.json — regenerate with
 *   cargo test write_v23_recursive_bundles_fixture -- --ignored --nocapture
 */
"use strict";

const { expect } = require("chai");
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

const FIXTURE_PATH = path.join(__dirname, "fixtures", "v23_recursive_bundles_e2e.json");
const FIXTURE_EXISTS = fs.existsSync(FIXTURE_PATH);

function bundleTuple(b) {
  return {
    inner: {
      traceRoot: b.inner.traceRoot,
      oodsComboPos: b.inner.oodsComboPos,
      oodsComboNeg: b.inner.oodsComboNeg,
      compRoot: b.inner.compRoot,
      friLayerRoots: b.inner.friLayerRoots,
      batchRoot: b.inner.batchRoot,
      treeDepth: b.inner.treeDepth,
      nQueries: b.inner.nQueries,
    },
    outerProof: b.outerProof,
    outerCommitment: b.outerCommitment,
    outerHints: b.outerHints,
    lastLayerEvals: b.lastLayerEvals,
  };
}

describe("BatchRegistryV7 × real V23 @ production n_queries=20", function () {
  let registry, recursive, fx, b10, b8;

  before(async function () {
    const [owner] = await ethers.getSigners();
    const vfri11 = await (await ethers.getContractFactory("QLSAVerifierVFRI11")).deploy();
    await vfri11.waitForDeployment();
    recursive = await (
      await ethers.getContractFactory("QLSAVerifierRecursive")
    ).deploy(await vfri11.getAddress());
    await recursive.waitForDeployment();
    registry = await (
      await ethers.getContractFactory("BatchRegistryV7")
    ).deploy(owner.address, await recursive.getAddress());
    await registry.waitForDeployment();

    if (FIXTURE_EXISTS) {
      fx = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
      b10 = bundleTuple(fx.bundle10);
      b8 = bundleTuple(fx.bundle8);
    }
  });

  it("fixture is the production V23 shape", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    expect(fx.bundle10.inner.treeDepth).to.equal(10);
    expect(fx.bundle8.inner.treeDepth).to.equal(8);
    expect(fx.bundle10.inner.nQueries).to.equal(20, "130-bit production security");
    expect(fx.bundle8.inner.nQueries).to.equal(20);
    expect(fx.bundle10.inner.friLayerRoots.length).to.equal(7, "num_folds = 6");
    // Last layers: 2^(10−6)=16 and 2^(8−6)=4 evaluations.
    expect(fx.bundle10.lastLayerEvals.length).to.equal(16);
    expect(fx.bundle8.lastLayerEvals.length).to.equal(4);
    // Cross-binding in both directions.
    expect(fx.bundle10.inner.batchRoot).to.equal(
      ethers.keccak256(ethers.concat([fx.merkleRoot, fx.bundle8.inner.traceRoot]))
    );
    expect(fx.bundle8.inner.batchRoot).to.equal(
      ethers.keccak256(ethers.concat([fx.merkleRoot, fx.bundle10.inner.traceRoot]))
    );
  });

  it("each REAL V23 group's recursive bundle verifies individually", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(900_000);
    for (const [name, b] of [["LOG=10", b10], ["LOG=8", b8]]) {
      const [ok] = await recursive.verifyRecursive.staticCall(
        b.inner, b.outerProof, b.outerCommitment, b.outerHints, b.lastLayerEvals,
        { gasLimit: 16_777_215n }
      );
      expect(ok, `${name} recursive bundle must verify`).to.equal(true);
    }
  });

  // THE headline path: ML-DSA-65 -> V23 (3505 cols) -> VFRI11 inner proofs at 20
  // FRI queries -> recursion -> one on-chain transaction. Direct verification of
  // the same statement does not fit a transaction at all (docs/conclusions.md
  // §2.3), so this is the only route to 130-bit on-chain soundness today.
  it("finalizes the full V23 batch at 130-bit security in ONE transaction", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(900_000);
    const tx = await registry.submitBatch(fx.merkleRoot, b10, b8, {
      gasLimit: 16_777_215n,
    });
    const rc = await tx.wait();
    console.log(`        [gas] V7 submitBatch, REAL V23 @ q=20 (130-bit) = ${rc.gasUsed}`);
    expect(rc.gasUsed).to.be.lessThan(
      16_777_216n,
      "production-security V23 must finalize within one transaction"
    );
    expect(await registry.isBatchFinalized(fx.merkleRoot)).to.equal(true);
    expect(await registry.batchCommitmentsLog10(fx.merkleRoot))
      .to.equal(fx.bundle10.outerCommitment);
    expect(await registry.batchCommitmentsLog8(fx.merkleRoot))
      .to.equal(fx.bundle8.outerCommitment);
  });

  it("rejects a tampered last layer on the real V23 bundle", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(900_000);
    const [owner] = await ethers.getSigners();
    const fresh = await (
      await ethers.getContractFactory("BatchRegistryV7")
    ).deploy(owner.address, await recursive.getAddress());
    const bad = JSON.parse(JSON.stringify(fx.bundle10));
    bad.lastLayerEvals[0] = (BigInt(bad.lastLayerEvals[0]) ^ 1n).toString();
    await expect(
      fresh.submitBatch(fx.merkleRoot, bundleTuple(bad), b8, { gasLimit: 16_777_215n })
    ).to.be.revertedWithCustomError(fresh, "Log10ProofInvalid");
  });
});
