const { expect } = require("chai");
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

// R4.5 — QLSAVerifierRecursive: one on-chain call that (1) replays the inner
// VFRI11 Fiat-Shamir channel from public roots (challenges become
// channel-derived public inputs) and (2) verifies the OUTER recursive-trace
// VFRI11 proof cross-bound to those inner publics. Fixture generated by
// `cargo test write_recursive_e2e_fixture -- --ignored` in stark_stwo.
describe("QLSAVerifierRecursive — recursive proof on-chain entry point (R4.5)", function () {
  let recursive;
  let fx;
  let innerTuple;

  before(async function () {
    const VFRI11 = await ethers.getContractFactory("QLSAVerifierVFRI11");
    const vfri11 = await VFRI11.deploy();
    await vfri11.waitForDeployment();

    const Recursive = await ethers.getContractFactory("QLSAVerifierRecursive");
    recursive = await Recursive.deploy(await vfri11.getAddress());
    await recursive.waitForDeployment();

    fx = JSON.parse(
      fs.readFileSync(path.join(__dirname, "fixtures", "recursive_e2e.json"), "utf8")
    );
    innerTuple = {
      traceRoot: fx.inner.traceRoot,
      oodsComboPos: fx.inner.oodsComboPos,
      oodsComboNeg: fx.inner.oodsComboNeg,
      compRoot: fx.inner.compRoot,
      friLayerRoots: fx.inner.friLayerRoots,
      batchRoot: fx.inner.batchRoot,
      treeDepth: fx.inner.treeDepth,
      nQueries: fx.inner.nQueries,
    };
  });

  it("outerBindingRoot matches the Rust keccak binding", async function () {
    const bound = await recursive.outerBindingRoot(
      fx.inner.traceRoot,
      fx.inner.friLayerRoots[fx.inner.friLayerRoots.length - 1]
    );
    expect(bound).to.equal(fx.outer.bindingRoot);
  });

  // The channel-replay half is fully on-chain today: replayChallenges derives the
  // recursion's public inputs from the inner proof's public roots, byte-identical
  // to the Rust reference vfri11_replay_channel (R4.2/R4.3).
  it("replayChallenges reproduces the Rust replay from the inner publics", async function () {
    const ch = await recursive.replayChallenges(innerTuple);
    expect(ch.zX.toString()).to.equal(fx.expected.zX, "replayed zX");
    expect(ch.queryIndices.length).to.equal(fx.expected.queryIndices.length);
    for (let i = 0; i < ch.queryIndices.length; i++) {
      expect(ch.queryIndices[i].toString()).to.equal(fx.expected.queryIndices[i]);
    }
  });

  it("replayChallenges shifts when the inner publics are tampered", async function () {
    const tampered = {
      ...innerTuple,
      traceRoot: "0x" + (BigInt(fx.inner.traceRoot) ^ 1n).toString(16).padStart(64, "0"),
    };
    const ch = await recursive.replayChallenges(tampered);
    // Full-root absorption of the trace root → the whole transcript moves.
    expect(ch.zX.toString()).to.not.equal(fx.expected.zX);
  });

  it("replayChallenges reverts on out-of-range inner params", async function () {
    await expect(
      recursive.replayChallenges({ ...innerTuple, treeDepth: 1 })
    ).to.be.revertedWith("RCR: treeDepth out of range");
    await expect(
      recursive.replayChallenges({ ...innerTuple, nQueries: 0 })
    ).to.be.revertedWith("RCR: nQueries out of range");
  });

  // MEASURED LIMIT (R4.6): the honest bundle's full path — replay + outer-proof
  // verification via the deployed VFRI11 — exceeds even a 29M gas call (Ethereum's
  // block ceiling), both at the original outer trace (log_size 7, 6 folds) and at
  // the compacted one (log_size 5, 1 query, 2 folds; hints 4.6 KB → 2.6 KB). The
  // rejection paths below DO execute on-chain because VFRI11's _checkCommitment
  // short-circuits before the expensive Merkle/Poseidon work. Verifying the outer
  // proof therefore needs a per-fold-split registry (one verify per transaction,
  // à la BatchRegistryV6) — tracked as R4.7. The outer→VFRI11 hint pipeline itself
  // is exercised off-chain by the Rust test_recursive_outer_trace_vfri11_hints.

  // R4.7 measurement: split the cost between the two halves so we know which one
  // to attack. Both run as eth_call, so we can estimate each independently.
  it("measures the gas of each half (diagnostic)", async function () {
    this.timeout(180_000);
    let replayGas = null, verifyGas = null;
    try {
      replayGas = await recursive.replayChallenges.estimateGas(innerTuple);
    } catch (e) {
      replayGas = `revert: ${(e.message || "").slice(0, 90)}`;
    }
    // Call the deployed VFRI11 DIRECTLY on the outer proof — isolates whether the
    // cost is in the outer verification or in this contract's wrapper/replay.
    const VFRI11 = await ethers.getContractFactory("QLSAVerifierVFRI11");
    const vfri11 = VFRI11.attach(await recursive.outerVerifier());
    try {
      verifyGas = await vfri11.verify.estimateGas(
        fx.outer.proof, fx.outer.commitment, fx.outer.bindingRoot, fx.outer.hints
      );
    } catch (e) {
      verifyGas = `revert: ${(e.message || "").slice(0, 90)}`;
    }
    console.log(`        [gas] replayChallenges = ${replayGas}`);
    console.log(`        [gas] VFRI11.verify(outer, direct) = ${verifyGas}`);
    expect(true).to.equal(true);
  });

  it("rejects the bundle when the inner publics are tampered", async function () {
    this.timeout(120_000);
    const tampered = {
      ...innerTuple,
      traceRoot: "0x" + (BigInt(fx.inner.traceRoot) ^ 1n).toString(16).padStart(64, "0"),
    };
    const [ok] = await recursive.verifyRecursive.staticCall(
      tampered,
      fx.outer.proof,
      fx.outer.commitment,
      fx.outer.hints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false, "outer proof must not verify for different inner publics");
  });

  it("rejects a wrong outer commitment", async function () {
    this.timeout(120_000);
    const bad = "0x" + (BigInt(fx.outer.commitment) ^ 1n).toString(16).padStart(32, "0");
    const [ok] = await recursive.verifyRecursive.staticCall(
      innerTuple,
      fx.outer.proof,
      bad,
      fx.outer.hints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false, "wrong outer commitment must not verify");
  });

  // NOTE: byte-level tampering of `outerHints` is deliberately NOT tested — a
  // corrupted ABI blob can make the deployed VFRI11's decoder allocate wildly
  // (panic 0x41) instead of returning false. That is a property of the deployed
  // verifier's decoder robustness, unrelated to this contract's logic.
});
