/**
 * QLSAVerifierVFRI10 — E2E test: VFRI9 protocol with the Poseidon2 t=4 backend.
 *
 * VFRI10 is byte-for-byte ABI-compatible with VFRI9 (same queryHints layout,
 * same last-layer FRI check).  The only change is the hash backend:
 *   Poseidon2MerkleVerifierW → Poseidon2MerkleVerifierT4   (t=4 wide Merkle)
 *   Poseidon2Channel         → Poseidon2ChannelT4          (t=4 Fiat-Shamir)
 *
 * The proof version marker is 4 (VFRI9 = 3).
 *
 * Fixture: vfri10_e2e.json — generated by the Rust bridge
 *   gen_vfri10_hints_from_cols_nfolds (6 cols, tree_depth=4, n_queries=2,
 *   num_folds=2).  Regenerate via:
 *     cargo test write_vfri10_e2e_fixture -- --ignored --nocapture
 *   The verifier is exercised directly with merkleRoot == the batch root used
 *   in generation (no cross-binding registry in this layer).
 * If the fixture file is absent, fixture-dependent tests are skipped.
 */
"use strict";

const { expect } = require("chai");
const { ethers } = require("hardhat");
const path = require("path");
const fs = require("fs");

const FIXTURE_PATH = path.join(__dirname, "fixtures", "vfri10_e2e.json");
const FIXTURE_EXISTS = fs.existsSync(FIXTURE_PATH);

const HINTS_ABI = [
  "uint128", "uint128", "bytes32", "uint128[]", "bytes32[]",
  "tuple(uint256,uint256,uint128,bytes32[],uint128,bytes32[],uint128,uint256,uint256,bytes32[],tuple(uint128,bytes32[],uint128,bytes32[])[])[]",
];

describe("QLSAVerifierVFRI10 — Poseidon2 t=4 backend E2E", function () {
  let verifier;
  let fixture;

  before(async function () {
    const Factory = await ethers.getContractFactory("QLSAVerifierVFRI10");
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();

    if (FIXTURE_EXISTS) {
      fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
    }
  });

  // ── Constants ───────────────────────────────────────────────────────────────

  it("exposes the expected constants", async function () {
    expect(await verifier.MIN_QUERIES()).to.equal(1n);
    expect(await verifier.MAX_QUERIES()).to.equal(64n);
    expect(await verifier.MAX_FOLD_ROUNDS()).to.equal(28n);
    expect(await verifier.MAX_LAST_LAYER_SIZE()).to.equal(1n << 16n);
  });

  // ── Fixture structural checks ───────────────────────────────────────────────

  it("fixture has the required keys", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    for (const k of ["proof", "commitment", "merkleRoot", "queryHints", "n_queries", "num_folds", "tree_depth"]) {
      expect(fixture, `missing key: ${k}`).to.have.property(k);
    }
  });

  it("proof version marker is 4 (VFRI10)", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const proof = Buffer.from(fixture.proof.slice(2), "hex");
    expect(proof.readBigUInt64LE(0)).to.equal(4n);
  });

  it("hints decode with the 6-slot VFRI9/VFRI10 ABI", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const abi = ethers.AbiCoder.defaultAbiCoder();
    const [, , , lastLayerEvals, friLayerRoots, hints] = abi.decode(HINTS_ABI, fixture.queryHints);
    // depth=4, 2 folds → 16/4 = 4 last-layer evaluations; L1 root + 2 fold roots = 3.
    expect(lastLayerEvals.length).to.equal(4);
    expect(friLayerRoots.length).to.equal(3);
    expect(hints.length).to.equal(fixture.n_queries);
  });

  it("commitment binds Blake2s(proof[:32] ‖ merkleRoot)[:16]", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const { createHash } = require("crypto");
    const proof = Buffer.from(fixture.proof.slice(2), "hex");
    const root = Buffer.from(fixture.merkleRoot.slice(2), "hex");
    const h = createHash("blake2s256");
    h.update(proof.slice(0, 32));
    h.update(root);
    expect("0x" + h.digest().slice(0, 16).toString("hex")).to.equal(fixture.commitment);
  });

  // ── verify() acceptance ─────────────────────────────────────────────────────

  it("verify() returns true for the valid fixture", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(60_000);
    let result = false;
    try {
      result = await verifier.verify.staticCall(
        fixture.proof, fixture.commitment, fixture.merkleRoot, fixture.queryHints,
        { gasLimit: 16_000_000n }
      );
    } catch (e) {
      expect.fail(`verify() reverted: ${e.message}`);
    }
    expect(result).to.equal(true, "VFRI10 verify must return true for a valid proof");
  });

  // ── verify() rejection paths ────────────────────────────────────────────────

  it("rejects a wrong merkleRoot (commitment + transcript mismatch)", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const wrongRoot = "0x" + "11".repeat(32);
    const ok = await verifier.verify.staticCall(
      fixture.proof, fixture.commitment, wrongRoot, fixture.queryHints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false);
  });

  it("rejects a zero commitment", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const ok = await verifier.verify.staticCall(
      fixture.proof, "0x" + "00".repeat(16), fixture.merkleRoot, fixture.queryHints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false);
  });

  it("rejects tampered last-layer evaluations", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const abi = ethers.AbiCoder.defaultAbiCoder();
    const decoded = abi.decode(HINTS_ABI, fixture.queryHints);
    const lastLayer = decoded[3].map((x) => BigInt(x));
    lastLayer[0] = lastLayer[0] ^ 1n; // flip one bit
    const tampered = abi.encode(HINTS_ABI, [
      decoded[0], decoded[1], decoded[2], lastLayer, decoded[4], decoded[5],
    ]);
    const ok = await verifier.verify.staticCall(
      fixture.proof, fixture.commitment, fixture.merkleRoot, tampered,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false);
  });

  it("rejects VFRI10 hints fed to the VFRI9 verifier (backend mismatch)", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const V9 = await (await ethers.getContractFactory("QLSAVerifierVFRI9")).deploy();
    await V9.waitForDeployment();
    const ok = await V9.verify.staticCall(
      fixture.proof, fixture.commitment, fixture.merkleRoot, fixture.queryHints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false, "t=4 hints must not verify under the t=2 backend");
  });

  it("rejects empty queryHints", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const ok = await verifier.verify.staticCall(
      fixture.proof, fixture.commitment, fixture.merkleRoot, "0x",
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false);
  });
});
