/**
 * QLSAVerifierVFRI6 — E2E test: NttBatch with off-chain OODS combo.
 *
 * VFRI6 changes from VFRI5:
 *   - Removes oodsEvalsPos[649] and oodsEvalsNeg[649] arrays from hints entirely
 *   - Prover precomputes oodsComboPos/Neg off-chain; passes only 2 uint128 values
 *   - Transcript: mixRoot → z_x → compAlpha [BEFORE OODS] → mixU32s(8 combo words)
 *                 → mixRoot(compRoot) → friAlpha → ...
 *   - Per-query hints: identical structure to VFRI5 (compValue + Merkle proof)
 *   - No Poseidon2 sponge, no lastLayerCoeffs (removed)
 *
 * Gas improvement for 649-col (12-poly) NttBatch:
 *   VFRI5: ~120 M gas (O(n_cols) oodsCombo computed once per call) — exceeds 15 M cap
 *   VFRI6: O(1) per call (2 uint128 values) → 649-col trace fits within 15 M gas ✓
 *
 * Calldata improvement:
 *   VFRI5: ~49 KB hints (oodsEvalsPos[649] + oodsEvalsNeg[649] + compRoot + per-query)
 *   VFRI6: ~7.2 KB hints (2 uint128 combos + compRoot + per-query only)
 *   Reduction: 6.8× smaller than VFRI5
 *
 * Fixture: 12 polys (649 cols), LOG_N_ROWS=10, n_queries=1, num_folds=9.
 * Generated by gen_ntt_batch_vfri6_hints(polys=12, root=bytes([0x55]*32), num_folds=9).
 */
"use strict";

const { expect } = require("chai");
const { ethers }  = require("hardhat");
const path        = require("path");
const fs          = require("fs");

describe("QLSAVerifierVFRI6 — NttBatch E2E (off-chain OODS combo, 649 cols)", function () {
  let verifier;
  const fixture = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "fixtures", "ntt_batch_vfri6_e2e.json"),
      "utf8"
    )
  );

  before(async function () {
    const Factory = await ethers.getContractFactory("QLSAVerifierVFRI6");
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();
  });

  // ── Fixture structural checks ─────────────────────────────────────────────

  it("fixture has correct n_polys and n_queries metadata", function () {
    expect(fixture.n_polys).to.equal(12);
    expect(fixture.n_queries).to.equal(1);
    expect(fixture.num_folds).to.equal(9);
  });

  it("fixture commitment follows Blake2s(proof[:32]‖merkleRoot)[:16]", function () {
    const { createHash } = require("crypto");
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    const rootBytes  = Buffer.from(fixture.merkleRoot.slice(2), "hex");
    const h = createHash("blake2s256");
    h.update(proofBytes.slice(0, 32));
    h.update(rootBytes);
    const expected = "0x" + h.digest().slice(0, 16).toString("hex");
    expect(fixture.commitment).to.equal(expected);
  });

  it("fixture queryHints is ~7 KB for 649 cols (6.8× smaller than VFRI5 ~49 KB)", function () {
    const hintsBytes = Buffer.from(fixture.queryHints.slice(2), "hex");
    // VFRI6: just 2 uint128 combos + compRoot + per-query Merkle proofs
    expect(hintsBytes.length).to.be.greaterThan(1_000);
    // Substantially smaller than VFRI5's ~49 KB — oodsEvalsPos/Neg arrays removed
    expect(hintsBytes.length).to.be.lessThan(15_000);
    console.log(`    ℹ VFRI6 649-col hints: ${hintsBytes.length} B vs VFRI5 ~49 KB (${(48928/hintsBytes.length).toFixed(1)}× smaller)`);
  });

  it("fixture proof[8:40] is non-zero (real NttBatch trace committed)", function () {
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    const traceRoot  = proofBytes.slice(8, 40);
    expect(traceRoot.equals(Buffer.alloc(32, 0))).to.equal(false);
  });

  it("fixture queryHints head is 5×32=160 bytes with non-zero compRoot at slot 2", function () {
    const hints = Buffer.from(fixture.queryHints.slice(2), "hex");
    // VFRI6 head = 5 × 32 = 160 bytes; compRoot at slot 2 = bytes 64..96
    expect(hints.length).to.be.greaterThan(160);
    const compRoot = hints.slice(64, 96);
    expect(compRoot.equals(Buffer.alloc(32, 0))).to.equal(false);
  });

  it("fixture queryHints head has 5 ABI slots (160 bytes) followed by bodies", function () {
    const hints = Buffer.from(fixture.queryHints.slice(2), "hex");
    // Head = 5 × 32 = 160 bytes
    // Slot 3 (bytes 96-127): offset to friLayerRoots — must be ≥ 160 (after head)
    const friRootsOffset = parseInt(hints.slice(96, 128).toString("hex"), 16);
    expect(friRootsOffset).to.be.greaterThanOrEqual(160);
    // Slot 4 (bytes 128-159): offset to QueryHints[] — must be > friRootsOffset
    const queryHintsOffset = parseInt(hints.slice(128, 160).toString("hex"), 16);
    expect(queryHintsOffset).to.be.greaterThan(friRootsOffset);
  });

  // ── VFRI5 hints must NOT validate with VFRI6 ─────────────────────────────

  it("VFRI5 hints rejected by VFRI6 verifier (different ABI layout)", async function () {
    const vfri5Fix = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "fixtures", "ntt_batch_vfri5_e2e.json"), "utf8"
      )
    );
    let rejected = false;
    try {
      const result = await verifier.verify(
        vfri5Fix.proof, vfri5Fix.commitment, vfri5Fix.merkleRoot, vfri5Fix.queryHints
      );
      rejected = !result;
    } catch (_) {
      rejected = true;
    }
    expect(rejected).to.equal(true);
  });

  // ── Early-rejection paths ─────────────────────────────────────────────────

  it("rejects zero commitment", async function () {
    const result = await verifier.verify(
      fixture.proof, "0x" + "00".repeat(16), fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects zero merkleRoot", async function () {
    const result = await verifier.verify(
      fixture.proof, fixture.commitment, ethers.ZeroHash, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects tampered commitment", async function () {
    const commitBytes = Buffer.from(fixture.commitment.slice(2), "hex");
    commitBytes[0] ^= 0x01;
    const result = await verifier.verify(
      fixture.proof, "0x" + commitBytes.toString("hex"), fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects tampered proof trace root", async function () {
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    proofBytes[8] ^= 0x01;
    const result = await verifier.verify(
      "0x" + proofBytes.toString("hex"), fixture.commitment, fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects all-zero oodsComboPos/Neg (sanity check)", async function () {
    const hints = Buffer.from(fixture.queryHints.slice(2), "hex");
    // Zero out slots 0 and 1 (oodsComboPos and oodsComboNeg)
    hints.fill(0, 0, 64);
    let rejected = false;
    try {
      const result = await verifier.verify(
        fixture.proof, fixture.commitment, fixture.merkleRoot, "0x" + hints.toString("hex")
      );
      rejected = !result;
    } catch (_) {
      rejected = true;
    }
    expect(rejected).to.equal(true);
  });

  // ── KEY VFRI6 IMPROVEMENT: 649-col trace fits within 15 M gas ────────────

  it("649-col VFRI6 1-query gas ≤ 15 M — O(n_cols) eliminated", async function () {
    this.timeout(60_000);
    let passed = false;
    let gasUsed;
    try {
      const tx = await verifier.verify.staticCall(
        fixture.proof, fixture.commitment, fixture.merkleRoot, fixture.queryHints,
        { gasLimit: 15_000_000n }
      );
      passed = true;
    } catch (e) {
      // If it hits gas limit, this test fails — that would mean VFRI6 didn't solve the bottleneck
      if (e.message && (e.message.includes("gas") || e.message.includes("Gas"))) {
        passed = false;
      } else {
        // Other errors (revert, etc.) — print for diagnosis
        console.log(`    ⚠ VFRI6 verify error: ${e.message?.slice(0, 100)}`);
        passed = false;
      }
    }
    expect(passed).to.equal(true,
      "649-col VFRI6 (1 query) should fit within 15 M gas — O(n_cols) work eliminated"
    );
  });

  // ── Calldata scale: VFRI6 vs VFRI5 ──────────────────────────────────────

  it("VFRI6 hints are 6.8× smaller than VFRI5 for 649 cols", function () {
    const vfri5Fix = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "fixtures", "ntt_batch_vfri5_e2e.json"), "utf8"
      )
    );
    const v5len = Buffer.from(vfri5Fix.queryHints.slice(2), "hex").length;
    const v6len = Buffer.from(fixture.queryHints.slice(2), "hex").length;
    const ratio = (v5len / v6len).toFixed(1);
    console.log(`    ℹ VFRI5: ${v5len} B vs VFRI6: ${v6len} B (${ratio}× smaller)`);
    expect(v6len).to.be.lessThan(v5len);
    // At least 4× smaller (oodsEvalsPos[649] + oodsEvalsNeg[649] = 20768 bytes removed)
    expect(v5len / v6len).to.be.greaterThan(4);
  });
});
