const { expect } = require("chai");
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

// R4.5 — QLSAVerifierRecursive: one on-chain call that (1) replays the inner
// VFRI11 Fiat-Shamir channel from public roots (challenges become
// channel-derived public inputs) and (2) verifies the OUTER recursive-trace
// VFRI11 proof cross-bound to those inner publics. Fixture generated by
// `cargo test write_recursive_e2e_fixture -- --ignored` in stark_stwo.
describe("QLSAVerifierRecursive — recursive proof on-chain entry point (R4.5)", function () {
  let recursive;
  let fx;
  let innerTuple;

  before(async function () {
    const VFRI11 = await ethers.getContractFactory("QLSAVerifierVFRI11");
    const vfri11 = await VFRI11.deploy();
    await vfri11.waitForDeployment();

    const Recursive = await ethers.getContractFactory("QLSAVerifierRecursive");
    recursive = await Recursive.deploy(await vfri11.getAddress());
    await recursive.waitForDeployment();

    fx = JSON.parse(
      fs.readFileSync(path.join(__dirname, "fixtures", "recursive_e2e.json"), "utf8")
    );
    innerTuple = {
      traceRoot: fx.inner.traceRoot,
      oodsComboPos: fx.inner.oodsComboPos,
      oodsComboNeg: fx.inner.oodsComboNeg,
      compRoot: fx.inner.compRoot,
      friLayerRoots: fx.inner.friLayerRoots,
      batchRoot: fx.inner.batchRoot,
      treeDepth: fx.inner.treeDepth,
      nQueries: fx.inner.nQueries,
    };
  });

  it("outerBindingRoot matches the Rust keccak binding", async function () {
    const bound = await recursive.outerBindingRoot(innerTuple);
    expect(bound).to.equal(fx.outer.bindingRoot);
  });

  // R4.7 regression: the binding root must move when ANY public inner field
  // changes — previously only traceRoot and the last fold root were bound, so
  // the OODS combos / compRoot / interior roots / batchRoot / depth / query
  // count could be swapped freely while an outer proof still verified.
  it("binding root is sensitive to every public inner field", async function () {
    const base = await recursive.outerBindingRoot(innerTuple);
    const variants = {
      oodsComboPos: { ...innerTuple, oodsComboPos: (BigInt(fx.inner.oodsComboPos) ^ 1n).toString() },
      oodsComboNeg: { ...innerTuple, oodsComboNeg: (BigInt(fx.inner.oodsComboNeg) ^ 1n).toString() },
      compRoot: { ...innerTuple, compRoot: "0x" + (BigInt(fx.inner.compRoot) ^ 1n).toString(16).padStart(64, "0") },
      interiorRoot: {
        ...innerTuple,
        friLayerRoots: fx.inner.friLayerRoots.map((r, i) =>
          i === 0 ? "0x" + (BigInt(r) ^ 1n).toString(16).padStart(64, "0") : r
        ),
      },
      batchRoot: { ...innerTuple, batchRoot: "0x" + (BigInt(fx.inner.batchRoot) ^ 1n).toString(16).padStart(64, "0") },
      treeDepth: { ...innerTuple, treeDepth: fx.inner.treeDepth + 1 },
      nQueries: { ...innerTuple, nQueries: fx.inner.nQueries + 1 },
    };
    for (const [name, v] of Object.entries(variants)) {
      const got = await recursive.outerBindingRoot(v);
      expect(got).to.not.equal(base, `binding must change when ${name} changes`);
    }
  });

  // The channel-replay half derives the
  // recursion's public inputs from the inner proof's public roots, byte-identical
  // to the Rust reference vfri11_replay_channel (R4.2/R4.3).
  it("replayChallenges reproduces the Rust replay from the inner publics", async function () {
    const ch = await recursive.replayChallenges(innerTuple);
    expect(ch.zX.toString()).to.equal(fx.expected.zX, "replayed zX");
    expect(ch.compAlpha.toString()).to.equal(fx.expected.compAlpha, "compAlpha");
    expect(ch.friAlpha.toString()).to.equal(fx.expected.friAlpha, "friAlpha");
    expect(ch.friAlphas.length).to.equal(fx.expected.friAlphas.length, "friAlphas length");
    for (let i = 0; i < ch.friAlphas.length; i++) {
      expect(ch.friAlphas[i].toString()).to.equal(fx.expected.friAlphas[i], `friAlphas[${i}]`);
    }
    expect(ch.queryIndices.length).to.equal(fx.expected.queryIndices.length);
    for (let i = 0; i < ch.queryIndices.length; i++) {
      expect(ch.queryIndices[i].toString()).to.equal(fx.expected.queryIndices[i]);
    }
  });

  it("replayChallenges shifts when the inner publics are tampered", async function () {
    const tampered = {
      ...innerTuple,
      traceRoot: "0x" + (BigInt(fx.inner.traceRoot) ^ 1n).toString(16).padStart(64, "0"),
    };
    const ch = await recursive.replayChallenges(tampered);
    // Full-root absorption of the trace root → the whole transcript moves.
    expect(ch.zX.toString()).to.not.equal(fx.expected.zX);
  });

  it("replayChallenges reverts on out-of-range inner params", async function () {
    await expect(
      recursive.replayChallenges({ ...innerTuple, treeDepth: 1 })
    ).to.be.revertedWith("RCR: treeDepth out of range");
    await expect(
      recursive.replayChallenges({ ...innerTuple, nQueries: 0 })
    ).to.be.revertedWith("RCR: nQueries out of range");
  });

  // R4.8 — THE HONEST BUNDLE VERIFIES ON-CHAIN IN ONE TRANSACTION.
  //
  // History: R4.6 recorded the full path (channel replay + outer-proof verification
  // via the deployed VFRI11) as exceeding the gas budget. Two things were wrong with
  // that conclusion. First, hardhat rejects a gasLimit above 16,777,216 (2^24,
  // EIP-7825) outright — the "29M call" was never executed, so the honest path had
  // never actually been run to completion. Second, the real cost was dominated by
  // Poseidon2 t=8 implementation overhead: ~106k gas per permutation, of which the
  // field arithmetic was only ~3k. The lazy-reduction + stack-state rewrite of
  // Poseidon2M31T8 cut that ~7x, taking the replay from 6.06M to ~0.8M and the outer
  // verify from 11.30M to ~1.55M.
  //
  // The recursion's on-chain contour is therefore CLOSED at t=8 (node collision
  // ~2^62), with ~7x headroom under the per-transaction cap.
  it("verifies the honest bundle in one transaction under the EIP-7825 cap", async function () {
    this.timeout(300_000);
    const [ok, ch] = await recursive.verifyRecursive.staticCall(
      innerTuple,
      fx.outer.proof,
      fx.outer.commitment,
      fx.outer.hints,
      { gasLimit: 16_777_215n }
    );
    expect(ok, "the honest recursive bundle must verify on-chain").to.equal(true);
    // The challenges returned alongside the proof are the replayed public inputs.
    expect(ch.zX.toString()).to.equal(fx.expected.zX);
    expect(ch.queryIndices.length).to.equal(fx.expected.queryIndices.length);
  });

  it("measures the gas of each half and of the whole call", async function () {
    this.timeout(300_000);
    const replayGas = await recursive.replayChallenges.estimateGas(innerTuple);
    // Call the deployed VFRI11 DIRECTLY on the outer proof — isolates the outer
    // verification from this contract's wrapper/replay.
    const VFRI11 = await ethers.getContractFactory("QLSAVerifierVFRI11");
    const vfri11 = VFRI11.attach(await recursive.outerVerifier());
    const verifyGas = await vfri11.verify.estimateGas(
      fx.outer.proof, fx.outer.commitment, fx.outer.bindingRoot, fx.outer.hints
    );
    const wholeGas = await recursive.verifyRecursive.estimateGas(
      innerTuple, fx.outer.proof, fx.outer.commitment, fx.outer.hints
    );
    console.log(`        [gas] replayChallenges            = ${replayGas}`);
    console.log(`        [gas] VFRI11.verify(outer, direct) = ${verifyGas}`);
    console.log(`        [gas] verifyRecursive (whole)      = ${wholeGas}`);
    // The whole call must fit a single transaction; each half must be a real cost.
    expect(wholeGas).to.be.lessThan(16_777_216n, "full recursive verify must fit one tx");
    expect(replayGas).to.be.greaterThan(0n);
    expect(verifyGas).to.be.greaterThan(0n);
  });

  it("rejects the bundle when the inner publics are tampered", async function () {
    this.timeout(120_000);
    const tampered = {
      ...innerTuple,
      traceRoot: "0x" + (BigInt(fx.inner.traceRoot) ^ 1n).toString(16).padStart(64, "0"),
    };
    const [ok] = await recursive.verifyRecursive.staticCall(
      tampered,
      fx.outer.proof,
      fx.outer.commitment,
      fx.outer.hints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false, "outer proof must not verify for different inner publics");
  });

  it("rejects a wrong outer commitment", async function () {
    this.timeout(120_000);
    const bad = "0x" + (BigInt(fx.outer.commitment) ^ 1n).toString(16).padStart(32, "0");
    const [ok] = await recursive.verifyRecursive.staticCall(
      innerTuple,
      fx.outer.proof,
      bad,
      fx.outer.hints,
      { gasLimit: 16_000_000n }
    );
    expect(ok).to.equal(false, "wrong outer commitment must not verify");
  });

  // NOTE: byte-level tampering of `outerHints` is deliberately NOT tested — a
  // corrupted ABI blob can make the deployed VFRI11's decoder allocate wildly
  // (panic 0x41) instead of returning false. That is a property of the deployed
  // verifier's decoder robustness, unrelated to this contract's logic.
});
