/**
 * QLSAVerifierVFRI4 — E2E test: NttBatch with Poseidon2 OODS sponge commitment.
 *
 * VFRI4 changes from VFRI3:
 *   - OODS eval channel mixing: mixU32s(n_cols*4 words) → mixU32s(4 words from Poseidon2 sponge)
 *   - queryHints ABI layout: identical to VFRI3
 *   - Result: channel transcript is column-count independent at mixing time
 *
 * Fixture: 1 poly (55 cols), LOG_N_ROWS=10, n_queries=1, num_folds=9.
 * Generated by gen_ntt_batch_vfri4_hints(polys=1, root=bytes(range(32)), num_folds=9).
 */
"use strict";

const { expect } = require("chai");
const { ethers }  = require("hardhat");
const path        = require("path");
const fs          = require("fs");

describe("QLSAVerifierVFRI4 — NttBatch E2E (Poseidon2 OODS sponge)", function () {
  let verifier;
  const fixture = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "fixtures", "ntt_batch_vfri4_e2e.json"),
      "utf8"
    )
  );

  before(async function () {
    const Factory = await ethers.getContractFactory("QLSAVerifierVFRI4");
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();
  });

  // ── Fixture structural checks ─────────────────────────────────────────────

  it("fixture has correct n_cols and n_polys metadata", function () {
    expect(fixture.n_cols).to.equal(55);
    expect(fixture.n_polys).to.equal(1);
    expect(fixture.n_queries).to.equal(1);
    expect(fixture.num_folds).to.equal(9);
  });

  it("fixture commitment follows Blake2s(proof[:32]‖merkleRoot)[:16]", function () {
    const { createHash } = require("crypto");
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    const rootBytes  = Buffer.from(fixture.merkleRoot.slice(2), "hex");
    const h = createHash("blake2s256");
    h.update(proofBytes.slice(0, 32));
    h.update(rootBytes);
    const expected = "0x" + h.digest().slice(0, 16).toString("hex");
    expect(fixture.commitment).to.equal(expected);
  });

  it("fixture queryHints is smaller than VFRI3 for same trace (Poseidon2 OODS is same ABI size)", function () {
    // VFRI4 queryHints ABI layout is identical to VFRI3; both have oodsEvalsPos/Neg arrays.
    // The gas difference is in the on-chain transcript computation, not calldata size.
    const hintsBytes = Buffer.from(fixture.queryHints.slice(2), "hex");
    expect(hintsBytes.length).to.be.greaterThan(0);
    // Fixture is ~14.6 KB (1 query, 9 folds, 55 cols).
    expect(hintsBytes.length).to.be.greaterThan(1000);
  });

  it("fixture proof[8:40] is non-zero (real NttBatch trace committed)", function () {
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    const traceRoot  = proofBytes.slice(8, 40);
    expect(traceRoot.equals(Buffer.alloc(32, 0))).to.equal(false);
  });

  // ── Early-rejection paths ─────────────────────────────────────────────────

  it("rejects zero commitment", async function () {
    const result = await verifier.verify(
      fixture.proof, "0x" + "00".repeat(16), fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects zero merkleRoot", async function () {
    const result = await verifier.verify(
      fixture.proof, fixture.commitment, ethers.ZeroHash, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects tampered commitment (binding check fails before FRI)", async function () {
    const commitBytes = Buffer.from(fixture.commitment.slice(2), "hex");
    commitBytes[0] ^= 0x01;
    const result = await verifier.verify(
      fixture.proof, "0x" + commitBytes.toString("hex"), fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects tampered proof trace root (commitment binding fails)", async function () {
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    proofBytes[8] ^= 0x01;
    const result = await verifier.verify(
      "0x" + proofBytes.toString("hex"), fixture.commitment, fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  // ── VFRI3 hints must NOT validate with VFRI4 (different transcript) ───────

  it("VFRI3 hints rejected by VFRI4 verifier (different Fiat-Shamir transcript)", async function () {
    const vfri3Fixture = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "fixtures", "ntt_batch_vfri3_e2e.json"), "utf8"
      )
    );
    // VFRI3 and VFRI4 have incompatible transcripts — VFRI3 hints must fail on VFRI4
    const result = await verifier.verify(
      vfri3Fixture.proof, vfri3Fixture.commitment, vfri3Fixture.merkleRoot, vfri3Fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  // ── Full on-chain FRI verification (Poseidon2 OODS sponge path) ──────────

  it("accepts valid NttBatch VFRI4 hints (full FRI verification)", async function () {
    this.timeout(120_000);
    const tx = await verifier.verify.staticCall(
      fixture.proof,
      fixture.commitment,
      fixture.merkleRoot,
      fixture.queryHints,
      { gasLimit: 15_000_000n }
    );
    expect(tx).to.equal(true);
  });

  it("rejects tampered last-layer coefficient", async function () {
    // queryHints ABI layout matches VFRI3:
    //   bytes   0-159: 5 head offsets (5 × 32 bytes)
    //   bytes 160-191: lastLayerCoeffs length word (= 2)
    //   bytes 192-207: lastLayerCoeffs[0] zero-padding
    //   bytes 208-223: lastLayerCoeffs[0] actual value  ← corrupt here
    const hints = Buffer.from(fixture.queryHints.slice(2), "hex");
    const corrupted = Buffer.from(hints);
    corrupted[210] ^= 0xff;
    const result = await verifier.verify(
      fixture.proof,
      fixture.commitment,
      fixture.merkleRoot,
      "0x" + corrupted.toString("hex")
    );
    expect(result).to.equal(false);
  });
});
