const { expect } = require("chai");
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

// R4.3 — the on-chain VFRI11 channel replay (RecursiveChannelReplay.sol) must
// reproduce, byte-for-byte, the challenges + query indices the Rust reference
// vfri11_replay_channel draws from the same public roots. Fixture generated by
// `cargo test write_vfri11_channel_replay_fixture -- --ignored` in stark_stwo.
describe("RecursiveChannelReplay — on-chain VFRI11 channel replay (R4.3)", function () {
  let harness;
  let fx;

  before(async function () {
    const Factory = await ethers.getContractFactory("RecursiveChannelReplayHarness");
    harness = await Factory.deploy();
    await harness.waitForDeployment();
    fx = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "fixtures", "vfri11_channel_replay.json"),
        "utf8"
      )
    );
  });

  it("reproduces the Rust reference challenges + query indices", async function () {
    const res = await harness.replay(
      fx.traceRoot,
      fx.oodsComboPos,
      fx.oodsComboNeg,
      fx.compRoot,
      fx.friLayerRoots,
      fx.batchRoot,
      fx.treeDepth,
      fx.nQueries
    );
    const [zX, compAlpha, friAlpha, friAlphas, queryIndices] = res;

    expect(zX.toString()).to.equal(fx.expected.zX, "zX");
    expect(compAlpha.toString()).to.equal(fx.expected.compAlpha, "compAlpha");
    expect(friAlpha.toString()).to.equal(fx.expected.friAlpha, "friAlpha");

    expect(friAlphas.length).to.equal(fx.expected.friAlphas.length, "friAlphas length");
    for (let i = 0; i < friAlphas.length; i++) {
      expect(friAlphas[i].toString()).to.equal(fx.expected.friAlphas[i], `friAlphas[${i}]`);
    }

    expect(queryIndices.length).to.equal(fx.expected.queryIndices.length, "queryIndices length");
    for (let i = 0; i < queryIndices.length; i++) {
      expect(queryIndices[i].toString()).to.equal(fx.expected.queryIndices[i], `queryIndices[${i}]`);
    }
  });

  it("a tampered trace root moves the drawn challenges (public-input soundness)", async function () {
    const tampered = "0x" + (BigInt(fx.traceRoot) ^ 1n).toString(16).padStart(64, "0");
    const res = await harness.replay(
      tampered,
      fx.oodsComboPos,
      fx.oodsComboNeg,
      fx.compRoot,
      fx.friLayerRoots,
      fx.batchRoot,
      fx.treeDepth,
      fx.nQueries
    );
    // zX must differ from the honest fixture value → the whole transcript shifts.
    expect(res[0].toString()).to.not.equal(fx.expected.zX);
  });

  it("rejects out-of-range structural params", async function () {
    await expect(
      harness.replay(
        fx.traceRoot, fx.oodsComboPos, fx.oodsComboNeg, fx.compRoot,
        fx.friLayerRoots, fx.batchRoot, 1 /* treeDepth < 2 */, fx.nQueries
      )
    ).to.be.revertedWith("RCR: treeDepth out of range");
    await expect(
      harness.replay(
        fx.traceRoot, fx.oodsComboPos, fx.oodsComboNeg, fx.compRoot,
        fx.friLayerRoots, fx.batchRoot, fx.treeDepth, 0 /* nQueries < 1 */
      )
    ).to.be.revertedWith("RCR: nQueries out of range");
    await expect(
      harness.replay(
        fx.traceRoot, fx.oodsComboPos, fx.oodsComboNeg, fx.compRoot,
        [] /* no roots */, fx.batchRoot, fx.treeDepth, fx.nQueries
      )
    ).to.be.revertedWith("RCR: need >= 1 fri layer root");
  });
});
