/**
 * BatchRegistryV4 — E2E test: full V23 dual-VFRI7 batch finalization with cross-proof binding.
 *
 * Architecture test:
 *   - BatchRegistryV4 computes cross-bound roots from proof bytes:
 *       boundRoot10 = keccak256(batchRoot ‖ proof8[8:40])
 *       boundRoot8  = keccak256(batchRoot ‖ proof10[8:40])
 *   - Each verifier call receives the cross-bound root as merkleRoot, not the raw batch root.
 *   - MockVerifierV4Dual checks Blake2s(proof[:32] ‖ merkleRoot)[:16] == commitment.
 *     With cross-binding, commitments must be bound to bound_root_* not to batchRoot.
 *   - Demonstrates that both LOG=10 (1298 cols) and LOG=8 (2206 cols) VFRI6 calls
 *     complete within 15M gas each.
 *
 * Fixture: full_v23_vfri7_cross_bound_e2e.json (generated by gen_mldsa_v23_vfri7_cross_bound_hints).
 * Fixture keys: merkleRoot, log10_proof, log10_commitment, log10_queryHints,
 *               log8_proof, log8_commitment, log8_queryHints,
 *               bound_root_10, bound_root_8, n_queries.
 */
"use strict";

const { expect } = require("chai");
const { ethers }  = require("hardhat");
const path        = require("path");
const fs          = require("fs");

describe("BatchRegistryV4 — Full V23 Dual-VFRI7 Cross-Bound E2E", function () {
  let registry, mockVerifier, vfri6;

  const fixture = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "fixtures", "full_v23_vfri7_cross_bound_e2e.json"),
      "utf8"
    )
  );

  before(async function () {
    const [signer] = await ethers.getSigners();

    // Mock verifier (commitment-binding only, no OODS) for registry logic tests.
    // MockVerifierV4Dual.verify() checks Blake2s(proof[:32] ‖ merkleRoot)[:16] == commitment
    // where merkleRoot is the cross-bound root passed by BatchRegistryV4.
    const MFactory = await ethers.getContractFactory("MockVerifierV4Dual");
    mockVerifier = await MFactory.deploy();
    await mockVerifier.waitForDeployment();

    // Real VFRI6 for gas characterization (returns false but does not run out of gas)
    const VFactory = await ethers.getContractFactory("QLSAVerifierVFRI6");
    vfri6 = await VFactory.deploy();
    await vfri6.waitForDeployment();

    // Registry wired to mock verifier
    const RFactory = await ethers.getContractFactory("BatchRegistryV4");
    registry = await RFactory.deploy(signer.address, await mockVerifier.getAddress());
    await registry.waitForDeployment();
  });

  // ── Fixture structural checks ─────────────────────────────────────────────

  it("fixture has both LOG=10 (1298 cols) and LOG=8 (2206 cols) groups", function () {
    const log10HintsLen = Buffer.from(fixture.log10_queryHints.slice(2), "hex").length;
    const log8HintsLen  = Buffer.from(fixture.log8_queryHints.slice(2),  "hex").length;
    expect(log10HintsLen).to.be.greaterThan(0, "LOG=10 hints present");
    expect(log8HintsLen).to.be.greaterThan(0,  "LOG=8 hints present");
    expect(fixture.n_queries).to.equal(1);
  });

  it("LOG=10 commitment binds Blake2s(proof[:32]‖bound_root_10)[:16]", function () {
    const { createHash } = require("crypto");
    const proof = Buffer.from(fixture.log10_proof.slice(2), "hex");
    const root  = Buffer.from(fixture.bound_root_10.slice(2), "hex");
    const h = createHash("blake2s256");
    h.update(proof.slice(0, 32));
    h.update(root);
    const expected = "0x" + h.digest().slice(0, 16).toString("hex");
    expect(fixture.log10_commitment).to.equal(expected);
  });

  it("LOG=8 commitment binds Blake2s(proof[:32]‖bound_root_8)[:16]", function () {
    const { createHash } = require("crypto");
    const proof = Buffer.from(fixture.log8_proof.slice(2), "hex");
    const root  = Buffer.from(fixture.bound_root_8.slice(2), "hex");
    const h = createHash("blake2s256");
    h.update(proof.slice(0, 32));
    h.update(root);
    const expected = "0x" + h.digest().slice(0, 16).toString("hex");
    expect(fixture.log8_commitment).to.equal(expected);
  });

  it("combined calldata is ~12.5 KB — both groups fit in one submission", function () {
    const log10Len = Buffer.from(fixture.log10_queryHints.slice(2), "hex").length;
    const log8Len  = Buffer.from(fixture.log8_queryHints.slice(2),  "hex").length;
    const total    = log10Len + log8Len;
    console.log(`    ℹ LOG=10: ${log10Len} B + LOG=8: ${log8Len} B = ${total} B total`);
    expect(total).to.be.lessThan(20_000);
  });

  // ── VFRI6 gas characterization (hints return false, but no gas overflow) ───

  it("LOG=10 (1298 cols) VFRI6 call completes within 15M gas (no revert)", async function () {
    this.timeout(60_000);
    let didNotRevert = false;
    try {
      await vfri6.verify.staticCall(
        fixture.log10_proof, fixture.log10_commitment,
        fixture.bound_root_10, fixture.log10_queryHints,
        { gasLimit: 15_000_000n }
      );
      didNotRevert = true;
    } catch (e) {
      if (e.message?.includes("gas") || e.message?.includes("Gas")) {
        didNotRevert = false;
      } else {
        didNotRevert = true;
      }
    }
    expect(didNotRevert).to.equal(true,
      "LOG=10 VFRI6 call should fit within 15M gas"
    );
    console.log(`    ℹ LOG=10 (1298 cols): completes within 15M gas ✓`);
  });

  it("LOG=8 (2206 cols) VFRI6 call completes within 15M gas (no revert)", async function () {
    this.timeout(60_000);
    let didNotRevert = false;
    try {
      await vfri6.verify.staticCall(
        fixture.log8_proof, fixture.log8_commitment,
        fixture.bound_root_8, fixture.log8_queryHints,
        { gasLimit: 15_000_000n }
      );
      didNotRevert = true;
    } catch (e) {
      if (e.message?.includes("gas") || e.message?.includes("Gas")) {
        didNotRevert = false;
      } else {
        didNotRevert = true;
      }
    }
    expect(didNotRevert).to.equal(true,
      "LOG=8 VFRI6 call should fit within 15M gas"
    );
    console.log(`    ℹ LOG=8 (2206 cols): completes within 15M gas ✓`);
  });

  // ── BatchRegistryV4 finalization (mock verifier) ──────────────────────────

  it("submitBatch finalizes when both mock proofs pass, emits BatchFinalized", async function () {
    this.timeout(30_000);
    const merkleRoot = fixture.merkleRoot;

    const tx = await registry.submitBatch(
      merkleRoot,
      fixture.log10_commitment,
      fixture.log10_proof,
      fixture.log10_queryHints,
      fixture.log8_commitment,
      fixture.log8_proof,
      fixture.log8_queryHints,
    );
    const receipt = await tx.wait();

    const event = receipt.logs.find(l => {
      try { return registry.interface.parseLog(l)?.name === "BatchFinalized"; }
      catch { return false; }
    });
    expect(event, "BatchFinalized event should be emitted").to.not.be.undefined;

    const parsed = registry.interface.parseLog(event);
    expect(parsed.args.merkleRoot).to.equal(merkleRoot);
    expect(parsed.args.commitmentLog10).to.equal(fixture.log10_commitment);
    expect(parsed.args.commitmentLog8).to.equal(fixture.log8_commitment);
  });

  it("batch is stored as finalized after submission", async function () {
    expect(await registry.isBatchFinalized(fixture.merkleRoot)).to.equal(true);
  });

  it("getCommitmentsLog10 returns the stored LOG=10 commitment", async function () {
    const c = await registry.getCommitmentsLog10(fixture.merkleRoot);
    expect(c).to.equal(fixture.log10_commitment);
  });

  it("getCommitmentsLog8 returns the stored LOG=8 commitment", async function () {
    const c = await registry.getCommitmentsLog8(fixture.merkleRoot);
    expect(c).to.equal(fixture.log8_commitment);
  });

  it("submitBatch reverts with BatchAlreadyFinalized on replay", async function () {
    await expect(
      registry.submitBatch(
        fixture.merkleRoot,
        fixture.log10_commitment,
        fixture.log10_proof,
        fixture.log10_queryHints,
        fixture.log8_commitment,
        fixture.log8_proof,
        fixture.log8_queryHints,
      )
    ).to.be.revertedWithCustomError(registry, "BatchAlreadyFinalized");
  });

  it("submitBatch reverts with Log10ProofInvalid if LOG=10 commitment is zero", async function () {
    const newRoot = "0x" + "aa".repeat(32);
    await expect(
      registry.submitBatch(
        newRoot,
        "0x" + "00".repeat(16),  // zero → MockVerifierV4Dual rejects immediately
        fixture.log10_proof,
        fixture.log10_queryHints,
        fixture.log8_commitment,
        fixture.log8_proof,
        fixture.log8_queryHints,
      )
    ).to.be.revertedWithCustomError(registry, "Log10ProofInvalid");
  });

  it("submitBatch reverts with Log8ProofInvalid if LOG=8 commitment is zero", async function () {
    const newRoot = "0x" + "bb".repeat(32);
    // BatchRegistryV4 computes boundRoot10 = keccak256(newRoot ‖ traceRoot8).
    // MockVerifierV4Dual checks Blake2s(proof10[:32] ‖ boundRoot10)[:16] == validCommit10.
    const { createHash } = require("crypto");
    const proof8Bytes = Buffer.from(fixture.log8_proof.slice(2), "hex");
    const traceRoot8  = "0x" + proof8Bytes.slice(8, 40).toString("hex");
    const boundRoot10ForNewRoot = ethers.keccak256(
      ethers.solidityPacked(["bytes32","bytes32"], [newRoot, traceRoot8])
    );
    const h10 = createHash("blake2s256");
    h10.update(Buffer.from(fixture.log10_proof.slice(2), "hex").slice(0, 32));
    h10.update(Buffer.from(boundRoot10ForNewRoot.slice(2), "hex"));
    const validCommit10 = "0x" + h10.digest().slice(0, 16).toString("hex");

    await expect(
      registry.submitBatch(
        newRoot,
        validCommit10,
        fixture.log10_proof,
        fixture.log10_queryHints,
        "0x" + "00".repeat(16),  // zero LOG=8 commitment → mock returns false
        fixture.log8_proof,
        fixture.log8_queryHints,
      )
    ).to.be.revertedWithCustomError(registry, "Log8ProofInvalid");
  });
});
