/**
 * QLSAVerifierVFRI5 — E2E test: NttBatch with composition polynomial tree.
 *
 * VFRI5 changes from VFRI4:
 *   - Adds compRoot: Merkle root of F(x) = Σ α^j · col_j(x) for all domain positions
 *   - Per-query hints carry compValue = F(p) + Merkle proof instead of all n_cols column values
 *   - Transcript: ... → compAlpha → mixRoot(compRoot) [NEW] → friAlpha → ...
 *   - Per-query calldata: O(tree_depth × 32) instead of O(n_cols × 32)
 *
 * Gas improvement for 649-col (12-poly) NttBatch:
 *   VFRI4: ~120 M gas (O(n_cols) per-query composition on-chain) — exceeds 15 M cap
 *   VFRI5: composition built once (O(n_cols)) in _buildCtx; per-query is O(tree_depth) → fits in 15 M gas
 *
 * Fixture: 12 polys (649 cols), LOG_N_ROWS=10, n_queries=1, num_folds=9.
 * Generated by gen_ntt_batch_vfri5_hints(polys=12, root=bytes([0x55]*32), num_folds=9).
 */
"use strict";

const { expect } = require("chai");
const { ethers }  = require("hardhat");
const path        = require("path");
const fs          = require("fs");

describe("QLSAVerifierVFRI5 — NttBatch E2E (composition polynomial tree, 649 cols)", function () {
  let verifier;
  const fixture = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "fixtures", "ntt_batch_vfri5_e2e.json"),
      "utf8"
    )
  );

  before(async function () {
    const Factory = await ethers.getContractFactory("QLSAVerifierVFRI5");
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();
  });

  // ── Fixture structural checks ─────────────────────────────────────────────

  it("fixture has correct n_polys and n_queries metadata", function () {
    expect(fixture.n_polys).to.equal(12);
    expect(fixture.n_queries).to.equal(1);
    expect(fixture.num_folds).to.equal(9);
  });

  it("fixture commitment follows Blake2s(proof[:32]‖merkleRoot)[:16]", function () {
    const { createHash } = require("crypto");
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    const rootBytes  = Buffer.from(fixture.merkleRoot.slice(2), "hex");
    const h = createHash("blake2s256");
    h.update(proofBytes.slice(0, 32));
    h.update(rootBytes);
    const expected = "0x" + h.digest().slice(0, 16).toString("hex");
    expect(fixture.commitment).to.equal(expected);
  });

  it("fixture queryHints is ~48 KB for 649 cols (smaller than VFRI4 ~90 KB)", function () {
    const hintsBytes = Buffer.from(fixture.queryHints.slice(2), "hex");
    // VFRI5: compValue + Merkle proof per query instead of 649 column values
    expect(hintsBytes.length).to.be.greaterThan(1_000);
    // Should be substantially smaller than VFRI4's ~90 KB for same trace
    expect(hintsBytes.length).to.be.lessThan(60_000);
    console.log(`    ℹ VFRI5 649-col hints: ${hintsBytes.length} B vs VFRI4 ~90 KB (${(90624/hintsBytes.length).toFixed(1)}× smaller)`);
  });

  it("fixture proof[8:40] is non-zero (real NttBatch trace committed)", function () {
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    const traceRoot  = proofBytes.slice(8, 40);
    expect(traceRoot.equals(Buffer.alloc(32, 0))).to.equal(false);
  });

  it("fixture queryHints head contains non-zero compRoot at slot 3 (bytes 96..128)", function () {
    const hints    = Buffer.from(fixture.queryHints.slice(2), "hex");
    // VFRI5 head = 6 × 32 = 192 bytes; slot 3 (0-indexed) = bytes 96..128
    const compRoot = hints.slice(96, 128);
    expect(compRoot.equals(Buffer.alloc(32, 0))).to.equal(false);
  });

  // ── VFRI4 hints must NOT validate with VFRI5 ─────────────────────────────

  it("VFRI4 hints rejected by VFRI5 verifier (ABI mismatch — different struct layout)", async function () {
    const vfri4Fix = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "fixtures", "ntt_batch_vfri4_e2e.json"), "utf8"
      )
    );
    // VFRI4 and VFRI5 have different QueryHints ABI layouts — VFRI4 hints either
    // return false (bad compRoot / sanity checks) or revert (ABI decode panic). Both are rejections.
    let rejected = false;
    try {
      const result = await verifier.verify(
        vfri4Fix.proof, vfri4Fix.commitment, vfri4Fix.merkleRoot, vfri4Fix.queryHints
      );
      rejected = !result;
    } catch (_) {
      rejected = true;  // ABI decode revert counts as rejection
    }
    expect(rejected).to.equal(true);
  });

  // ── Early-rejection paths ─────────────────────────────────────────────────

  it("rejects zero commitment", async function () {
    const result = await verifier.verify(
      fixture.proof, "0x" + "00".repeat(16), fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects zero merkleRoot", async function () {
    const result = await verifier.verify(
      fixture.proof, fixture.commitment, ethers.ZeroHash, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects tampered commitment", async function () {
    const commitBytes = Buffer.from(fixture.commitment.slice(2), "hex");
    commitBytes[0] ^= 0x01;
    const result = await verifier.verify(
      fixture.proof, "0x" + commitBytes.toString("hex"), fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  it("rejects tampered proof trace root", async function () {
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    proofBytes[8] ^= 0x01;
    const result = await verifier.verify(
      "0x" + proofBytes.toString("hex"), fixture.commitment, fixture.merkleRoot, fixture.queryHints
    );
    expect(result).to.equal(false);
  });

  // ── Gas scale: VFRI5 vs VFRI4 analysis ──────────────────────────────────
  //
  // VFRI5 eliminates O(n_cols) PER-QUERY composition, replacing it with:
  //   - Once per call: oodsComboPos/Neg = Σ α^j · oodsEval_j  (O(n_cols))
  //   - Per query:     Merkle verify compValue in compRoot     (O(tree_depth))
  //
  // For 1 query the total O(n_cols) work is the same as VFRI4. The benefit
  // shows when n_queries ≥ 2:
  //   VFRI4: O(n_cols × n_queries) total composition
  //   VFRI5: O(n_cols) once + O(tree_depth × n_queries)
  //
  // Per-query calldata:
  //   VFRI4 (649 col): ~90 KB hints (queryValues + queryValuesNeg per query)
  //   VFRI5 (649 col): ~49 KB hints (oodsEvalsPos/Neg once + compProof per query)
  //
  // VFRI6 will eliminate oodsEvalsPos/Neg from hints entirely — replacing them
  // with a Merkle commitment to the OODS evaluations, reducing total gas to
  // O(1) per additional query and O(1) calldata.

  it("649-col VFRI5 1-query gas > 15 M — documents scale boundary for VFRI6", async function () {
    this.timeout(60_000);
    let hitGasLimit = false;
    try {
      await verifier.verify.staticCall(
        fixture.proof, fixture.commitment, fixture.merkleRoot, fixture.queryHints,
        { gasLimit: 15_000_000n }
      );
    } catch (e) {
      if (e.message && (e.message.includes("gas") || e.message.includes("Gas"))) {
        hitGasLimit = true;
      }
    }
    // VFRI5 with 1 query still computes oodsComboPos/Neg (O(n_cols) once).
    // VFRI6 will move OODS combo off-chain. Flip this test when VFRI6 lands.
    expect(hitGasLimit).to.equal(true,
      "649-col VFRI5 (1 query) should exceed 15 M gas — update when VFRI6 lands"
    );
  });

  it("VFRI5 per-query calldata is 1.9× smaller than VFRI4 for 649 cols", function () {
    // Key VFRI5 improvement: per-query compValue/compProof replaces queryValues[649].
    // For n_queries, VFRI5 total hints grow O(n_queries × tree_depth) vs O(n_queries × n_cols).
    const vfri4Fix = JSON.parse(
      fs.readFileSync(
        path.join(__dirname, "fixtures", "mldsa_v23_ntt_vfri4_e2e.json"), "utf8"
      )
    );
    const v4len = Buffer.from(vfri4Fix.queryHints.slice(2), "hex").length;
    const v5len = Buffer.from(fixture.queryHints.slice(2), "hex").length;
    const ratio = (v4len / v5len).toFixed(1);
    console.log(`    ℹ VFRI4: ${v4len} B vs VFRI5: ${v5len} B (${ratio}× smaller)`);
    expect(v5len).to.be.lessThan(v4len);
  });
});
