/**
 * End-to-end test: verify that hints generated by `gen_poseidon2_vfri3_real`
 * (real Poseidon2 trace, barycentric OODS, non-constant last layer) pass
 * the on-chain `QLSAVerifierVFRI3.verify()` check.
 *
 * The fixture `contracts/test/fixtures/vfri3_real_e2e.json` was produced by
 * running `stark.prover.gen_poseidon2_vfri3_real([1..8], bytes(range(32)), 2)`.
 */
"use strict";

const { expect } = require("chai");
const { ethers }  = require("hardhat");
const path        = require("path");
const fs          = require("fs");

describe("QLSAVerifierVFRI3 — end-to-end real-trace hints", function () {
  let verifier;

  before(async function () {
    const Factory = await ethers.getContractFactory("QLSAVerifierVFRI3");
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();
  });

  it("accepts real Poseidon2 trace hints (2-query fixture)", async function () {
    const fixturePath = path.join(__dirname, "fixtures", "vfri3_real_e2e.json");
    const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

    const result = await verifier.verify(
      fixture.proof,
      fixture.commitment,
      fixture.merkleRoot,
      fixture.queryHints
    );

    expect(result).to.equal(true);
  });

  it("rejects tampered proof trace-root (mismatched hint traceRoot)", async function () {
    const fixturePath = path.join(__dirname, "fixtures", "vfri3_real_e2e.json");
    const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

    // Flip a byte in proof[8:40] (the embedded trace root) and recompute commitment
    // to keep the commitment check passing. Hints still carry the original traceRoot,
    // so the verifier's traceRoot cross-check should fail.
    const proofBytes = Buffer.from(fixture.proof.slice(2), "hex");
    proofBytes[8] ^= 0x01;                          // flip byte inside embedded trace root
    const badProof = "0x" + proofBytes.toString("hex");

    // Recompute commitment = Blake2s(badProof[:32] ‖ merkleRoot)[:16]
    const { createHash } = require("crypto");
    const h = createHash("blake2s256");
    h.update(proofBytes.slice(0, 32));
    h.update(Buffer.from(fixture.merkleRoot.slice(2), "hex"));
    const newCommitment = "0x" + h.digest().slice(0, 16).toString("hex");

    const result = await verifier.verify(
      badProof,
      newCommitment,
      fixture.merkleRoot,
      fixture.queryHints
    );

    expect(result).to.equal(false);
  });

  it("rejects tampered commitment", async function () {
    const fixturePath = path.join(__dirname, "fixtures", "vfri3_real_e2e.json");
    const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

    // Flip the last byte of the 16-byte commitment
    const commitBytes = Buffer.from(fixture.commitment.slice(2), "hex");
    commitBytes[15] ^= 0x01;
    const badCommit = "0x" + commitBytes.toString("hex");

    const result = await verifier.verify(
      fixture.proof,
      badCommit,
      fixture.merkleRoot,
      fixture.queryHints
    );

    expect(result).to.equal(false);
  });

  it("rejects tampered merkleRoot", async function () {
    const fixturePath = path.join(__dirname, "fixtures", "vfri3_real_e2e.json");
    const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

    const rootBytes = Buffer.from(fixture.merkleRoot.slice(2), "hex");
    rootBytes[0] ^= 0x01;
    const badRoot = "0x" + rootBytes.toString("hex");

    const result = await verifier.verify(
      fixture.proof,
      fixture.commitment,
      badRoot,
      fixture.queryHints
    );

    expect(result).to.equal(false);
  });

  it("rejects tampered queryHints (flipped byte)", async function () {
    const fixturePath = path.join(__dirname, "fixtures", "vfri3_real_e2e.json");
    const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8"));

    // Flip a byte deep in the hints (skip first 32 bytes which are the lastLayerCoeffs offset)
    const hintsBytes = Buffer.from(fixture.queryHints.slice(2), "hex");
    hintsBytes[500] ^= 0x01;
    const badHints = "0x" + hintsBytes.toString("hex");

    const result = await verifier.verify(
      fixture.proof,
      fixture.commitment,
      fixture.merkleRoot,
      badHints
    );

    expect(result).to.equal(false);
  });
});
