/**
 * QLSAVerifierVFRI10 — full V23 cross-bound E2E (Poseidon2 t=4 backend).
 *
 * Mirrors QLSAVerifierVFRI9E2E but with the t=4 verifier.  VFRI10 is
 * ABI-identical to VFRI9; only the hash backend changes (t=2 → t=4), so the
 * BatchRegistryV5 cross-binding (boundRoot = keccak256(merkleRoot ‖ traceRoot))
 * is unchanged.
 *
 * Fixture: full_v23_vfri10_cross_bound_e2e.json — generated by
 *   stark.prover.gen_mldsa_v23_vfri10_cross_bound_hints (V23 inputs seed=16600,
 *   n_queries=1, num_folds=6).  Both LOG groups carry version marker 4.
 *
 * Gas note: t=4 permutations cost ~3× t=2.  This test measures verify() gas and
 * asserts only that it succeeds; the LOG=10 group (1298 cols) at depth 10 with a
 * 128-leaf last layer is the heaviest path.  If verify exceeds the node gas cap,
 * the documented MVP-6 follow-up is fewer last-layer evals (more folds) or
 * RPO256.  If the fixture is absent, fixture-dependent tests skip.
 */
"use strict";

const { expect } = require("chai");
const { ethers } = require("hardhat");
const path = require("path");
const fs = require("fs");

const FIXTURE_PATH = path.join(__dirname, "fixtures", "full_v23_vfri10_cross_bound_e2e.json");
const FIXTURE_EXISTS = fs.existsSync(FIXTURE_PATH);

function boundRoot(merkleRoot, proofHex) {
  const proof = Buffer.from(proofHex.slice(2), "hex");
  const traceRoot = "0x" + proof.slice(8, 40).toString("hex");
  return ethers.keccak256(ethers.solidityPacked(["bytes32", "bytes32"], [merkleRoot, traceRoot]));
}

describe("QLSAVerifierVFRI10 — full V23 cross-bound E2E", function () {
  let verifier, registry5, signer;
  let fixture, boundRoot10, boundRoot8;

  before(async function () {
    [signer] = await ethers.getSigners();

    const Factory = await ethers.getContractFactory("QLSAVerifierVFRI10");
    verifier = await Factory.deploy();
    await verifier.waitForDeployment();

    const R5 = await ethers.getContractFactory("BatchRegistryV5");
    registry5 = await R5.deploy(signer.address, await verifier.getAddress());
    await registry5.waitForDeployment();

    if (FIXTURE_EXISTS) {
      fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
      // BatchRegistryV5 binds the LOG=10 proof to the LOG=8 trace root and vice versa.
      boundRoot10 = boundRoot(fixture.merkleRoot, fixture.log8_proof);
      boundRoot8 = boundRoot(fixture.merkleRoot, fixture.log10_proof);
    }
  });

  // ── Structural checks ───────────────────────────────────────────────────────

  it("fixture has the required keys", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    for (const k of ["merkleRoot", "log10_proof", "log10_commitment", "log10_queryHints",
                     "log8_proof", "log8_commitment", "log8_queryHints"]) {
      expect(fixture, `missing key: ${k}`).to.have.property(k);
    }
  });

  it("both proofs carry version marker 4 (VFRI10)", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    expect(Buffer.from(fixture.log10_proof.slice(2), "hex").readBigUInt64LE(0)).to.equal(4n);
    expect(Buffer.from(fixture.log8_proof.slice(2), "hex").readBigUInt64LE(0)).to.equal(4n);
  });

  it("commitments bind Blake2s(proof[:32] ‖ boundRoot)[:16]", function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    const { createHash } = require("crypto");
    for (const [proofHex, commit, br] of [
      [fixture.log10_proof, fixture.log10_commitment, boundRoot10],
      [fixture.log8_proof, fixture.log8_commitment, boundRoot8],
    ]) {
      const h = createHash("blake2s256");
      h.update(Buffer.from(proofHex.slice(2), "hex").slice(0, 32));
      h.update(Buffer.from(br.slice(2), "hex"));
      expect("0x" + h.digest().slice(0, 16).toString("hex")).to.equal(commit);
    }
  });

  // ── verify() acceptance ─────────────────────────────────────────────────────

  it("verify() returns true for LOG=10 with boundRoot10", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(120_000);
    let result = false;
    try {
      result = await verifier.verify.staticCall(
        fixture.log10_proof, fixture.log10_commitment, boundRoot10, fixture.log10_queryHints,
        { gasLimit: 16_700_000n }
      );
    } catch (e) {
      expect.fail(`LOG=10 verify() reverted (likely gas): ${e.message}`);
    }
    expect(result).to.equal(true, "VFRI10 LOG=10 verify must return true");
  });

  it("verify() returns true for LOG=8 with boundRoot8", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(120_000);
    let result = false;
    try {
      result = await verifier.verify.staticCall(
        fixture.log8_proof, fixture.log8_commitment, boundRoot8, fixture.log8_queryHints,
        { gasLimit: 16_700_000n }
      );
    } catch (e) {
      expect.fail(`LOG=8 verify() reverted (likely gas): ${e.message}`);
    }
    expect(result).to.equal(true, "VFRI10 LOG=8 verify must return true");
  });

  // ── Binding rejections ──────────────────────────────────────────────────────

  it("verify() rejects the raw merkleRoot (must use boundRoot10)", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(60_000);
    const ok = await verifier.verify.staticCall(
      fixture.log10_proof, fixture.log10_commitment, fixture.merkleRoot, fixture.log10_queryHints,
      { gasLimit: 16_700_000n }
    );
    expect(ok).to.equal(false);
  });

  it("verify() rejects VFRI9 (t=2) hints fed to the t=4 verifier", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(60_000);
    const V9_FIXTURE = path.join(__dirname, "fixtures", "full_v23_vfri9_cross_bound_e2e.json");
    if (!fs.existsSync(V9_FIXTURE)) { this.skip(); return; }
    const f9 = JSON.parse(fs.readFileSync(V9_FIXTURE, "utf8"));
    let rejected = false;
    try {
      const ok = await verifier.verify.staticCall(
        f9.log10_proof, f9.log10_commitment, f9.bound_root_10, f9.log10_queryHints,
        { gasLimit: 16_700_000n }
      );
      rejected = ok === false;
    } catch (e) {
      rejected = true; // ABI/transcript mismatch revert is also a rejection
    }
    expect(rejected).to.equal(true, "t=4 verifier must not accept t=2 hints");
  });

  // ── BatchRegistryV5 integration — single-transaction dual verify ─────────────
  //
  // History: until 2026-07-30 the two t=4 V23 verifies cost ~10.6M + ~7.9M gas,
  // so `submitBatch` (which runs BOTH in one transaction) overran the 16,777,216
  // (2^24, EIP-7825) per-tx cap and ran out of gas in the second verify.  That is
  // why BatchRegistryV6 splits the groups across two transactions.
  //
  // The lazy-reduction + stack-state rewrite of Poseidon2M31T4 cut the per-
  // permutation cost ~4x (see Poseidon2M31T4.sol "Lazy reduction"), bringing each
  // group to ~2.1M / ~1.6M and the combined single-transaction submit to ~3.7M —
  // comfortably inside the cap.  The per-group split is now an option, not a
  // requirement.
  //
  // NOTE on measurement: use the ACTUAL gasUsed from a sent transaction, not
  // `estimateGas`.  For a transaction that makes nested calls, hardhat's estimator
  // over-provisions (63/64 rule applied per call frame) and can report >18M for a
  // transaction whose real cost is ~6M — then trip its own 2^24 cap check.

  it("dual-VFRI10 submitBatch finalizes in ONE transaction inside the 16.7M cap", async function () {
    if (!FIXTURE_EXISTS) { this.skip(); return; }
    this.timeout(300_000);
    const tx = await registry5.submitBatch(
      fixture.merkleRoot,
      fixture.log10_commitment, fixture.log10_proof, fixture.log10_queryHints,
      fixture.log8_commitment, fixture.log8_proof, fixture.log8_queryHints,
      { gasLimit: 16_777_215n }
    );
    const rc = await tx.wait();
    console.log(`        [gas] dual-VFRI10 submitBatch used = ${rc.gasUsed}`);
    expect(rc.gasUsed).to.be.lessThan(
      16_777_216n,
      "two t=4 V23 verifies must fit one transaction under the EIP-7825 cap"
    );
    expect(await registry5.isBatchFinalized(fixture.merkleRoot)).to.equal(true);
  });

  // ── Deployment-only checks (run even without fixture) ────────────────────────

  describe("deployment checks (no fixture required)", function () {
    it("QLSAVerifierVFRI10 deploys and exposes VFRI9-compatible constants", async function () {
      expect(await verifier.MAX_LAST_LAYER_SIZE()).to.equal(65536n);
      expect(await verifier.MAX_FOLD_ROUNDS()).to.equal(28n);
    });

    it("BatchRegistryV5 wires the VFRI10 verifier address", async function () {
      expect(await registry5.verifier()).to.equal(await verifier.getAddress());
    });
  });
});
