#!/usr/bin/env bash
# QLSA MVP-6 — Testnet Deployment Script (VFRI10 + BatchRegistryV6)
#
# Deploys QLSAVerifierVFRI10 + BatchRegistryV6 to the configured network, then
# saves the addresses to .env.deployed for use by e2e.py and monitor.py.
#
# BatchRegistryV6 verifies each V23 trace group in its own transaction (each
# Poseidon2 t=4 verify ≤16.7M gas), so the full V23 batch finalizes across two
# transactions while preserving cross-proof binding.
#
# Prerequisites:
#   cp .env.example .env       # fill in RPC_URL and DEPLOYER_PRIVATE_KEY
#   cd contracts && npm install
#   cd stark_stwo && maturin develop --features python --release
#
# Usage:
#   bash testnet/deploy_v6.sh [--network sepolia]
set -euo pipefail

NETWORK="${1:-sepolia}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== QLSA MVP-6 — Testnet Deployment (VFRI10 + BatchRegistryV6) ==="
echo "Network : $NETWORK"
echo "Repo    : $REPO_ROOT"
echo

# ── 1. Build STARK binary ─────────────────────────────────────────────────────
BINARY="$REPO_ROOT/stark_stwo/target/release/qlsa-stark-stwo"
if [ ! -f "$BINARY" ]; then
  echo "[1/4] Building Stwo Circle STARK binary…"
  (cd "$REPO_ROOT/stark_stwo" && cargo +nightly-2025-07-01 build --release)
else
  echo "[1/4] STARK binary already built: $BINARY"
fi

# ── 2. Install contract dependencies ─────────────────────────────────────────
echo "[2/4] Installing Hardhat dependencies…"
(cd "$REPO_ROOT/contracts" && npm install --silent)

# ── 3. Deploy contracts ───────────────────────────────────────────────────────
echo "[3/4] Deploying QLSAVerifierVFRI10 + BatchRegistryV6 to $NETWORK…"
DEPLOY_OUT=$(cd "$REPO_ROOT/contracts" && \
  npx hardhat run scripts/deploy_v6.js --network "$NETWORK" 2>&1)

echo "$DEPLOY_OUT"

# Parse deployed addresses from the deploy script output.
VERIFIER_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'QLSAVerifierVFRI10 deployed to: \K0x[0-9a-fA-F]{40}')
REGISTRY_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'BatchRegistryV6 deployed to: \K0x[0-9a-fA-F]{40}')

if [ -z "$VERIFIER_ADDR" ] || [ -z "$REGISTRY_ADDR" ]; then
  echo "ERROR: Could not parse deployed addresses from deploy output."
  echo "Expected lines matching:"
  echo "  'QLSAVerifierVFRI10 deployed to: 0x...'"
  echo "  'BatchRegistryV6 deployed to: 0x...'"
  exit 1
fi

# ── 4. Save addresses ─────────────────────────────────────────────────────────
DEPLOYED_FILE="$REPO_ROOT/.env.deployed"
echo "[4/4] Saving addresses to $DEPLOYED_FILE"
cat > "$DEPLOYED_FILE" <<EOF
# Auto-generated by testnet/deploy_v6.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK
# Stack: QLSAVerifierVFRI10 + BatchRegistryV6 (MVP-6, per-group split)
VERIFIER_ADDRESS=$VERIFIER_ADDR
REGISTRY_ADDRESS=$REGISTRY_ADDR
EOF

echo
echo "=== Deployment complete ==="
echo "  QLSAVerifierVFRI10 : $VERIFIER_ADDR"
echo "  BatchRegistryV6    : $REGISTRY_ADDR"
echo
echo "Next steps:"
echo "  # Copy addresses to .env:"
echo "  cat .env.deployed >> .env"
echo "  # Run E2E demo (VFRI10 + per-group split, num_folds=6 for gas):"
echo "  python -m testnet.e2e --stack v6 --txs 8 --dry-run"
echo "  python -m testnet.e2e --stack v6 --txs 8"
echo "  # Monitor BatchFinalized events:"
echo "  python -m testnet.monitor"
