#!/usr/bin/env bash
# QLSA MVP-8 — Testnet Deployment Script (VFRI11 + QLSAVerifierRecursive + BatchRegistryV7)
#
# Deploys QLSAVerifierRecursive + BatchRegistryV7 to the configured network, then
# saves the addresses to .env.deployed for use by e2e.py and monitor.py.
#
# The registry does NOT verify the V23 groups' proofs itself. It verifies, per
# group, a STARK attesting that the inner VFRI11 proof was verified, plus the
# cheap on-chain half the recursion leaves outside the circuit (Fiat-Shamir
# channel replay + last-layer bounded-degree check).
#
# Why: at the production 20 FRI queries — 130-bit soundness — DIRECT verification
# of a V23 group no longer fits an Ethereum transaction, while this route
# finalizes the whole batch in one (~13.2M gas measured end to end).
#
# Below roughly 2 queries the DIRECT v7 stack is cheaper. This is a soundness
# mechanism, not a gas optimisation — see docs/conclusions.md.
#
# Prerequisites:
#   cp .env.example .env       # fill in RPC_URL and DEPLOYER_PRIVATE_KEY
#   cd contracts && npm install
#   cd stark_stwo && maturin develop --features python --release
#
# Usage:
#   bash testnet/deploy_v8.sh [--network sepolia]
set -euo pipefail

NETWORK="sepolia"
while [ $# -gt 0 ]; do
  case "$1" in
    --network) NETWORK="${2:?--network requires a value}"; shift 2;;
    --network=*) NETWORK="${1#*=}"; shift;;
    -h|--help) sed -n '2,17p' "$0"; exit 0;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 1;;
  esac
done
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== QLSA MVP-8 — Testnet Deployment (VFRI11 + Recursive + BatchRegistryV7) ==="
echo "Network : $NETWORK"
echo "Repo    : $REPO_ROOT"
echo

# ── 1. Build STARK binary ─────────────────────────────────────────────────────
BINARY="$REPO_ROOT/stark_stwo/target/release/qlsa-stark-stwo"
if [ ! -f "$BINARY" ]; then
  echo "[1/4] Building Stwo Circle STARK binary…"
  (cd "$REPO_ROOT/stark_stwo" && cargo +nightly-2025-07-01 build --release)
else
  echo "[1/4] STARK binary already built: $BINARY"
fi

# ── 2. Install contract dependencies ─────────────────────────────────────────
echo "[2/4] Installing Hardhat dependencies…"
(cd "$REPO_ROOT/contracts" && npm install --silent)

# ── 3. Deploy contracts ───────────────────────────────────────────────────────
echo "[3/4] Deploying QLSAVerifierRecursive + BatchRegistryV7 to $NETWORK…"
DEPLOY_OUT=$(cd "$REPO_ROOT/contracts" && \
  npx hardhat run scripts/deploy_v8.js --network "$NETWORK" 2>&1)

echo "$DEPLOY_OUT"

# Parse deployed addresses from the deploy script output.
VERIFIER_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'QLSAVerifierRecursive deployed to: \K0x[0-9a-fA-F]{40}')
REGISTRY_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'BatchRegistryV7 deployed to: \K0x[0-9a-fA-F]{40}')

if [ -z "$VERIFIER_ADDR" ] || [ -z "$REGISTRY_ADDR" ]; then
  echo "ERROR: Could not parse deployed addresses from deploy output."
  echo "Expected lines matching:"
  echo "  'QLSAVerifierRecursive deployed to: 0x...'"
  echo "  'BatchRegistryV7 deployed to: 0x...'"
  exit 1
fi

# ── 4. Save addresses ─────────────────────────────────────────────────────────
DEPLOYED_FILE="$REPO_ROOT/.env.deployed"
echo "[4/4] Saving addresses to $DEPLOYED_FILE"
# The file holds only public addresses, but the documented next step appends it
# to .env (which carries DEPLOYER_PRIVATE_KEY); create it 0600 to set the right
# expectation and avoid a world-readable artifact.
( umask 077; : > "$DEPLOYED_FILE" )
cat > "$DEPLOYED_FILE" <<EOF
# Auto-generated by testnet/deploy_v8.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK
# Stack: QLSAVerifierRecursive + BatchRegistryV7 (MVP-8, recursive, 130-bit)
VERIFIER_ADDRESS=$VERIFIER_ADDR
REGISTRY_ADDRESS=$REGISTRY_ADDR
EOF

echo
echo "=== Deployment complete ==="
echo "  QLSAVerifierRecursive : $VERIFIER_ADDR"
echo "  BatchRegistryV7    : $REGISTRY_ADDR"
echo
echo "Next steps:"
echo "  # Copy addresses to .env:"
echo "  cat .env.deployed >> .env"
echo "  # Run E2E demo (recursive, n_queries=20 -> 130-bit soundness):"
echo "  # v7 is the DEFAULT stack, so --stack may be omitted:"
echo "  python -m testnet.e2e --stack v8 --txs 8 --dry-run"
echo "  python -m testnet.e2e --stack v8 --txs 8"
echo "  # Monitor BatchFinalized events:"
echo "  python -m testnet.monitor"
