#!/usr/bin/env bash
# QLSA MVP-7 — Testnet Deployment Script (VFRI10 + BatchRegistryV5)
#
# Deploys QLSAVerifierVFRI11 + BatchRegistryV5 to the configured network, then
# saves the addresses to .env.deployed for use by e2e.py and monitor.py.
#
# VFRI11 uses the Poseidon2 t=8 hash backend: Merkle nodes carry 4 M31 words
# (124 bits) instead of t=4's two (62 bits), so node-collision cost rises from
# ~2^31 to ~2^62.  BatchRegistryV5 verifies BOTH V23 trace groups in ONE atomic
# transaction (~6.06M gas measured), which the t=8 backend only became able to do
# after the R4.8 Poseidon2 rewrite (2026-07-30).
#
# Use deploy_v6.sh instead for the t=4 stack with a per-group split (lower peak
# gas per transaction: ~2.15M + ~1.70M, at the weaker ~2^31 node bound).
#
# Prerequisites:
#   cp .env.example .env       # fill in RPC_URL and DEPLOYER_PRIVATE_KEY
#   cd contracts && npm install
#   cd stark_stwo && maturin develop --features python --release
#
# Usage:
#   bash testnet/deploy_v7.sh [--network sepolia]
set -euo pipefail

NETWORK="sepolia"
while [ $# -gt 0 ]; do
  case "$1" in
    --network) NETWORK="${2:?--network requires a value}"; shift 2;;
    --network=*) NETWORK="${1#*=}"; shift;;
    -h|--help) sed -n '2,17p' "$0"; exit 0;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 1;;
  esac
done
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== QLSA MVP-7 — Testnet Deployment (VFRI10 + BatchRegistryV5) ==="
echo "Network : $NETWORK"
echo "Repo    : $REPO_ROOT"
echo

# ── 1. Build STARK binary ─────────────────────────────────────────────────────
BINARY="$REPO_ROOT/stark_stwo/target/release/qlsa-stark-stwo"
if [ ! -f "$BINARY" ]; then
  echo "[1/4] Building Stwo Circle STARK binary…"
  (cd "$REPO_ROOT/stark_stwo" && cargo +nightly-2025-07-01 build --release)
else
  echo "[1/4] STARK binary already built: $BINARY"
fi

# ── 2. Install contract dependencies ─────────────────────────────────────────
echo "[2/4] Installing Hardhat dependencies…"
(cd "$REPO_ROOT/contracts" && npm install --silent)

# ── 3. Deploy contracts ───────────────────────────────────────────────────────
echo "[3/4] Deploying QLSAVerifierVFRI11 + BatchRegistryV5 to $NETWORK…"
DEPLOY_OUT=$(cd "$REPO_ROOT/contracts" && \
  npx hardhat run scripts/deploy_v7.js --network "$NETWORK" 2>&1)

echo "$DEPLOY_OUT"

# Parse deployed addresses from the deploy script output.
VERIFIER_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'QLSAVerifierVFRI11 deployed to: \K0x[0-9a-fA-F]{40}')
REGISTRY_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'BatchRegistryV5 deployed to: \K0x[0-9a-fA-F]{40}')

if [ -z "$VERIFIER_ADDR" ] || [ -z "$REGISTRY_ADDR" ]; then
  echo "ERROR: Could not parse deployed addresses from deploy output."
  echo "Expected lines matching:"
  echo "  'QLSAVerifierVFRI11 deployed to: 0x...'"
  echo "  'BatchRegistryV5 deployed to: 0x...'"
  exit 1
fi

# ── 4. Save addresses ─────────────────────────────────────────────────────────
DEPLOYED_FILE="$REPO_ROOT/.env.deployed"
echo "[4/4] Saving addresses to $DEPLOYED_FILE"
# The file holds only public addresses, but the documented next step appends it
# to .env (which carries DEPLOYER_PRIVATE_KEY); create it 0600 to set the right
# expectation and avoid a world-readable artifact.
( umask 077; : > "$DEPLOYED_FILE" )
cat > "$DEPLOYED_FILE" <<EOF
# Auto-generated by testnet/deploy_v7.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK
# Stack: QLSAVerifierVFRI11 + BatchRegistryV5 (MVP-7, t=8, single submitBatch)
VERIFIER_ADDRESS=$VERIFIER_ADDR
REGISTRY_ADDRESS=$REGISTRY_ADDR
EOF

echo
echo "=== Deployment complete ==="
echo "  QLSAVerifierVFRI11 : $VERIFIER_ADDR"
echo "  BatchRegistryV5    : $REGISTRY_ADDR"
echo
echo "Next steps:"
echo "  # Copy addresses to .env:"
echo "  cat .env.deployed >> .env"
echo "  # Run E2E demo (VFRI11 t=8, single submitBatch, num_folds=6):"
echo "  python -m testnet.e2e --stack v7 --txs 8 --dry-run"
echo "  python -m testnet.e2e --stack v7 --txs 8"
echo "  # Monitor BatchFinalized events:"
echo "  python -m testnet.monitor"
