#!/usr/bin/env bash
# QLSA Phase 6 — Testnet Deployment Script
#
# Deploys QLSAVerifierBound + BatchRegistryV2 to the configured network,
# then saves the addresses to .env.deployed for use by e2e.py and monitor.py.
#
# Prerequisites:
#   cp .env.example .env       # fill in RPC_URL and DEPLOYER_PRIVATE_KEY
#   cd contracts && npm install
#
# Usage:
#   bash testnet/deploy.sh [--network cardona]
set -euo pipefail

NETWORK="${1:-cardona}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== QLSA Phase 6 — Testnet Deployment ==="
echo "Network : $NETWORK"
echo "Repo    : $REPO_ROOT"
echo

# ── 1. Build STARK binary ─────────────────────────────────────────────────────
BINARY="$REPO_ROOT/stark_stwo/target/release/qlsa-stark-stwo"
if [ ! -f "$BINARY" ]; then
  echo "[1/4] Building Stwo Circle STARK binary…"
  (cd "$REPO_ROOT/stark_stwo" && cargo +nightly-2025-07-01 build --release)
else
  echo "[1/4] STARK binary already built: $BINARY"
fi

# ── 2. Install contract dependencies ─────────────────────────────────────────
echo "[2/4] Installing Hardhat dependencies…"
(cd "$REPO_ROOT/contracts" && npm install --silent)

# ── 3. Deploy contracts ───────────────────────────────────────────────────────
echo "[3/4] Deploying contracts to $NETWORK…"
DEPLOY_OUT=$(cd "$REPO_ROOT/contracts" && \
  npx hardhat run scripts/deploy.js --network "$NETWORK" 2>&1)

echo "$DEPLOY_OUT"

# Parse deployed addresses from the deploy script output.
VERIFIER_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'QLSAVerifierBound deployed to: \K0x[0-9a-fA-F]{40}')
REGISTRY_ADDR=$(echo "$DEPLOY_OUT" | grep -oP 'BatchRegistryV2 deployed to: \K0x[0-9a-fA-F]{40}')  # fixed: was 'deployed'

if [ -z "$VERIFIER_ADDR" ] || [ -z "$REGISTRY_ADDR" ]; then
  echo "ERROR: Could not parse deployed addresses from deploy output."
  exit 1
fi

# ── 4. Save addresses ─────────────────────────────────────────────────────────
DEPLOYED_FILE="$REPO_ROOT/.env.deployed"
echo "[4/4] Saving addresses to $DEPLOYED_FILE"
cat > "$DEPLOYED_FILE" <<EOF
# Auto-generated by testnet/deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK
VERIFIER_ADDRESS=$VERIFIER_ADDR
REGISTRY_ADDRESS=$REGISTRY_ADDR
EOF

echo
echo "=== Deployment complete ==="
echo "  QLSAVerifierBound : $VERIFIER_ADDR"
echo "  BatchRegistryV2   : $REGISTRY_ADDR"
echo
echo "Next steps:"
echo "  # Add VERIFIER_ADDRESS and REGISTRY_ADDRESS to your .env, then:"
echo "  python -m testnet.e2e --txs 8"
echo "  python -m testnet.monitor"
echo "  docker compose up -d"
